version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - env | grep -e AI_MODEL_NAME -e AI_BASE_URL -e AI_API_KEY -e ADMIN_USERNAME -e ADMIN_PASSWORD -e AUTH_TOKEN -e POSTGRES_URL >> .env.production
        - cp .env.production .env.development
        - cp .env.production .env.local
        - cp .env.production .env
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - "**/*"
  cache:
    paths:
      - node_modules/**/*
      - .next/cache/**/*
